In [ ]:
import numpy as np    #importing numpy library as np

In [ ]:
arr=np.arange(15)     #creating a 1d numpy array containing intezers form 0-14

NameError: name 'np' is not defined

In [ ]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [ ]:
arr.reshape(3,5)     #reshaping the arr into 3*5 2d numpy array but didn't saved

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [ ]:
print(arr)           #printing the arr

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [ ]:
arr.reshape(5,3)     #reshaping the arr into 5*3 2d numpy array but didn't saved

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [ ]:
arr.shape            #tells you the shape of the arr

(15,)

In [ ]:
arr.size             #it tells you the no. of element

15

In [ ]:
arr.ndim             #it tells you the dimension of the arr

1

In [ ]:
arr=arr.reshape(3,5)   #now we have commited the change

In [ ]:
arr.size

15

In [ ]:
arr.ndim            #now it becomes 2D

2

In [ ]:
arr.dtype           #it will tells you the datatype of the element stored in arr

dtype('int64')

In [ ]:
arr1=np.zeros((2,3,4),np.int32)   #creating new array containing 0 and defining the size 2*3*4 of int32 bits datatype

In [ ]:
arr1

array([[[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]]], dtype=int32)

In [ ]:
arr2=np.ones((5,2))            #creating new array containing 0 and defining the size 5*2

In [ ]:
arr2

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [ ]:
np.empty((3,3))          #actual values in the array will depend on the state of the memory at the time the array is created

array([[3.1 , 0.  , 0.5 ],
       [0.  , 0.77, 0.11],
       [0.  , 0.  , 1.  ]])

In [ ]:
np.arange(10,32,.8)     #this will create a 1D array arange(start,end,step)

array([10. , 10.8, 11.6, 12.4, 13.2, 14. , 14.8, 15.6, 16.4, 17.2, 18. ,
       18.8, 19.6, 20.4, 21.2, 22. , 22.8, 23.6, 24.4, 25.2, 26. , 26.8,
       27.6, 28.4, 29.2, 30. , 30.8, 31.6])

In [ ]:
x=np.linspace(0,2,100)  #here it will give 100 numbers in between [0,2)

In [ ]:
y=np.sin(x)           #assinging sin function value to y where x is the independent variable

In [ ]:
print(y)

[0.         0.02020065 0.04039305 0.06056897 0.08072016 0.10083842
 0.12091552 0.14094328 0.16091352 0.18081808 0.20064886 0.22039774
 0.24005668 0.25961766 0.27907268 0.2984138  0.31763315 0.33672286
 0.35567516 0.3744823  0.39313661 0.41163048 0.42995636 0.44810678
 0.46607431 0.48385164 0.5014315  0.51880673 0.53597023 0.55291499
 0.56963411 0.58612075 0.60236819 0.6183698  0.63411905 0.64960951
 0.66483486 0.67978889 0.69446549 0.70885867 0.72296256 0.73677141
 0.75027957 0.76348154 0.77637192 0.78894546 0.80119703 0.81312162
 0.82471437 0.83597055 0.84688556 0.85745496 0.86767441 0.87753977
 0.88704699 0.8961922  0.90497167 0.91338181 0.9214192  0.92908054
 0.93636273 0.94326277 0.94977786 0.95590534 0.96164271 0.96698762
 0.9719379  0.97649152 0.98064663 0.98440153 0.98775469 0.99070474
 0.99325047 0.99539085 0.99712501 0.99845223 0.99937197 0.99988386
 0.99998769 0.99968342 0.99897117 0.99785123 0.99632407 0.99439029
 0.99205069 0.98930624 0.98615803 0.98260737 0.9786557  0.9743

In [ ]:
import pandas as pd      #importing pandas library as pd

In [ ]:
df=np.arange(20).reshape(5,4)    #using 2 functions simultaneously

In [ ]:
df

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [ ]:
df1=pd.DataFrame(data=np.arange(20).reshape(5,4),index=['r1','r2','r3','r4','r5'],columns=['c1','c2','c3','c4'])
#Dataframe is a data structure in pandas function where we can perform different operation
#here we are assinging row and columns names

In [ ]:
df1

c1  c2  c3  c4
r1   0   1   2   3
r2   4   5   6   7
r3   8   9  10  11
r4  12  13  14  15
r5  16  17  18  19

In [ ]:
df1.head()    #this function will return the top 5 rows

c1  c2  c3  c4
r1   0   1   2   3
r2   4   5   6   7
r3   8   9  10  11
r4  12  13  14  15
r5  16  17  18  19

In [ ]:
df1.tail()        #this will return you last 5 rows

c1  c2  c3  c4
r1   0   1   2   3
r2   4   5   6   7
r3   8   9  10  11
r4  12  13  14  15
r5  16  17  18  19

In [ ]:
type(df1)           #asking for the datatype of df1

pandas.core.frame.DataFrame

In [ ]:
type(df)           #asking for the datatype of df

numpy.ndarray

In [ ]:
df1

c1  c2  c3  c4
r1   0   1   2   3
r2   4   5   6   7
r3   8   9  10  11
r4  12  13  14  15
r5  16  17  18  19

In [ ]:
df1.describe()          # provides descriptive statistics of the data in a DataFrame

c1         c2         c3         c4
count   5.000000   5.000000   5.000000   5.000000
mean    8.000000   9.000000  10.000000  11.000000
std     6.324555   6.324555   6.324555   6.324555
min     0.000000   1.000000   2.000000   3.000000
25%     4.000000   5.000000   6.000000   7.000000
50%     8.000000   9.000000  10.000000  11.000000
75%    12.000000  13.000000  14.000000  15.000000
max    16.000000  17.000000  18.000000  19.000000

In [ ]:
ar=np.array([0,4,8,12,16])

In [ ]:
np.std(ar)         #return the standard deviation of the ar

5.656854249492381

In [ ]:
a=df1[['c1','c2']]       #return you the columns which is mentioned

In [ ]:
a

c1  c2
r1   0   1
r2   4   5
r3   8   9
r4  12  13
r5  16  17

In [ ]:
type(a)

pandas.core.frame.DataFrame

In [ ]:
type(df1['c1'])
#Series is a another data structure in pandas which is 1D

pandas.core.series.Series

In [ ]:
df1.loc[['r1','r2','r3']]   #location function is used to access any row or columns or mix of both

c1  c2  c3  c4
r1   0   1   2   3
r2   4   5   6   7
r3   8   9  10  11

In [ ]:
df1.loc[['r1','r2','r3'],['c3']]

c3
r1   2
r2   6
r3  10

In [ ]:
df1.head()

c1  c2  c3  c4
r1   0   1   2   3
r2   4   5   6   7
r3   8   9  10  11
r4  12  13  14  15
r5  16  17  18  19

In [ ]:
df1.iloc[1:4,2:5]      #unlike location function ,index location is used to access the elkements using index(usually 0-based index)

c3  c4
r2   6   7
r3  10  11
r4  14  15

In [ ]:
df1.iloc[1:,2:]

c3  c4
r2   6   7
r3  10  11
r4  14  15
r5  18  19

In [ ]:
df1.iloc[:,[0,3]]

c1  c4
r1   0   3
r2   4   7
r3   8  11
r4  12  15
r5  16  19

In [ ]:
df1.iloc[1:,1:].values            #converting dataframe into array

array([[ 5,  6,  7],
       [ 9, 10, 11],
       [13, 14, 15],
       [17, 18, 19]])

In [ ]:
df1.isnull().sum()            #cheching for null values

c1    0
c2    0
c3    0
c4    0
dtype: int64

In [ ]:
df1.iloc[1,1]

5

In [ ]:
df1.iloc[1,1]=np.NaN           #assigning new values to dataframe

In [ ]:
df1

c1    c2  c3  c4
r1   0   1.0   2   3
r2   4   NaN   6   7
r3   8   9.0  10  11
r4  12  13.0  14  15
r5  16  17.0  18  19

In [ ]:
df1.isnull().sum()

c1    0
c2    1
c3    0
c4    0
dtype: int64

In [ ]:
df2=pd.DataFrame(data=[[1,2,3,4,5],[10,11,13,np.NaN,15]],index=[0,1],columns=[0,1,2,3,4])

In [ ]:
df2

0   1   2    3   4
0   1   2   3  4.0   5
1  10  11  13  NaN  15

In [ ]:
df2.isnull().sum()

0    0
1    0
2    0
3    1
4    0
dtype: int64

In [ ]:
df2.isnull()

0      1      2      3      4
0  False  False  False  False  False
1  False  False  False   True  False

In [ ]:
df2.head()

0   1   2    3   4
0   1   2   3  4.0   5
1  10  11  13  NaN  15

In [ ]:
df2[0].value_counts()         #gives you the value count

1     1
10    1
Name: 0, dtype: int64

In [ ]:
df2.iloc[0,4]=15

In [ ]:
df2

0   1   2    3   4
0   1   2   3  4.0  15
1  10  11  13  NaN  15

In [ ]:
df2[4].value_counts()

15    2
Name: 4, dtype: int64

In [ ]:
df2[4].mean()

15.0

In [ ]:
df2>4

0      1      2      3     4
0  False  False  False  False  True
1   True   True   True  False  True

In [ ]:
df2[df2>4]           #using conditional statement

0     1     2   3   4
0   NaN   NaN   NaN NaN  15
1  10.0  11.0  13.0 NaN  15

In [ ]:
df2[df2[3]>1]

0  1  2    3   4
0  1  2  3  4.0  15

In [ ]:
df3=pd.read_csv('titanic.csv')     #converting csv(comma seperated values) file into dataframe

In [ ]:
df3

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
886                              Montvila, Rev. Juozas    male  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch            Ticket     Fare Cabin Embarked  
0        0         A/5 21171   7.2500   NaN        S  
1        0          PC 17599  71.2833   C85        C  
2        0  STON/O2. 3101282   7.9250   NaN        S  
3        0            113803  53.1000  C123        S  
4        0            373450   8.0500   NaN        S  
..     ...               ...      ...   ...      ...  
886      0            211536  13.0000   NaN        S  
887      0            112053  30.0000   B42        S  
888      2        W./C. 6607  23.4500   NaN        S  
889      0            111369  30.0000  C148        C  
890      0            370376   7.7500   NaN        Q  

[891 rows x 12 columns]

In [ ]:
df3.describe()     #describing all the columns whose datatypes are intezer

PassengerId    Survived      Pclass         Age       SibSp  \
count   891.000000  891.000000  891.000000  714.000000  891.000000   
mean    446.000000    0.383838    2.308642   29.699118    0.523008   
std     257.353842    0.486592    0.836071   14.526497    1.102743   
min       1.000000    0.000000    1.000000    0.420000    0.000000   
25%     223.500000    0.000000    2.000000   20.125000    0.000000   
50%     446.000000    0.000000    3.000000   28.000000    0.000000   
75%     668.500000    1.000000    3.000000   38.000000    1.000000   
max     891.000000    1.000000    3.000000   80.000000    8.000000   

            Parch        Fare  
count  891.000000  891.000000  
mean     0.381594   32.204208  
std      0.806057   49.693429  
min      0.000000    0.000000  
25%      0.000000    7.910400  
50%      0.000000   14.454200  
75%      0.000000   31.000000  
max      6.000000  512.329200

In [ ]:
type(df3)

pandas.core.frame.DataFrame

In [ ]:
df3.head(7)

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   
5            6         0       3   
6            7         0       1   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   
5                                   Moran, Mr. James    male   NaN      0   
6                            McCarthy, Mr. Timothy J    male  54.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S  
5      0            330877   8.4583   NaN        Q  
6      0             17463  51.8625   E46        S

In [ ]:
df3[df3['Age']>60].mean()

<ipython-input-524-880ba8347334>:1: FutureWarning: The default value of numeric_only in DataFrame.mean is deprecated. In a future version, it will default to False. In addition, specifying 'numeric_only=None' is deprecated. Select only valid columns or specify the value of numeric_only to silence this warning.
  df3[df3['Age']>60].mean()


PassengerId    432.545455
Survived         0.227273
Pclass           1.590909
Age             66.022727
SibSp            0.136364
Parch            0.272727
Fare            41.371214
dtype: float64

In [ ]:
df3['Age'].mean()

29.69911764705882

In [ ]:
df3['Age'].median()

28.0

In [ ]:
df3['Age'].std()

14.526497332334042

In [ ]:
df3.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [ ]:
df3.index

RangeIndex(start=0, stop=891, step=1)

In [ ]:
df3[['Age','Name','Sex','Fare','Survived']].head()    #returning head of  specefic columns

Age                                               Name     Sex     Fare  \
0  22.0                            Braund, Mr. Owen Harris    male   7.2500   
1  38.0  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  71.2833   
2  26.0                             Heikkinen, Miss. Laina  female   7.9250   
3  35.0       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  53.1000   
4  35.0                           Allen, Mr. William Henry    male   8.0500   

   Survived  
0         0  
1         1  
2         1  
3         1  
4         0

In [ ]:
df3['Survived'].sum()

342

df3.shape[0]m

In [ ]:
df3.shape

(891, 12)

In [ ]:
type(df3)

pandas.core.frame.DataFrame

In [ ]:
students= { 'name':['ramu','aakash','raman','raju'],
          'age':['18','21','20','20'] ,
           'marks':['90','65','72','88']}

#creating dictionary for students

In [ ]:
students

{'name': ['ramu', 'aakash', 'raman', 'raju'],
 'age': ['18', '21', '20', '20'],
 'marks': ['90', '65', '72', '88']}

In [ ]:
df4=pd.DataFrame(students)     #converting students into dataframe

In [ ]:
df4

name age marks
0    ramu  18    90
1  aakash  21    65
2   raman  20    72
3    raju  20    88

In [ ]:
df4.marks

0    90
1    65
2    72
3    88
Name: marks, dtype: object

In [ ]:
df4.set_index('name')       #setting up the index/row column and but not saved

age marks
name            
ramu    18    90
aakash  21    65
raman   20    72
raju    20    88

In [ ]:
df4

name age marks
0    ramu  18    90
1  aakash  21    65
2   raman  20    72
3    raju  20    88

In [ ]:
df4.loc[0]

name     ramu
age        18
marks      90
Name: 0, dtype: object

In [ ]:
df4

name age marks
0    ramu  18    90
1  aakash  21    65
2   raman  20    72
3    raju  20    88

In [ ]:
df4.set_index('marks',inplace=True)     #here we are using inplace to save the change

In [ ]:
df4

name age
marks            
90       ramu  18
65     aakash  21
72      raman  20
88       raju  20

In [ ]:
df4.reset_index()               #resetting the index to previous index

marks    name age
0    90    ramu  18
1    65  aakash  21
2    72   raman  20
3    88    raju  20

In [ ]:
df4.reset_index()

marks    name age
0    90    ramu  18
1    65  aakash  21
2    72   raman  20
3    88    raju  20

In [ ]:
df4.reset_index(inplace=True)

In [ ]:
df4['name']=['raju','aakash','raman','piyush']    #changing the name column

In [ ]:
df4

marks    name age
0    90    raju  18
1    65  aakash  21
2    72   raman  20
3    88  piyush  20

In [ ]:
df4.loc[[0],['marks']]

marks
0    90

In [ ]:
df4.set_index('name',inplace=True)

In [ ]:
df4

marks age
name            
raju      90  18
aakash    65  21
raman     72  20
piyush    88  20

In [ ]:
df4.index

Index(['raju', 'aakash', 'raman', 'piyush'], dtype='object', name='name')

In [ ]:
df4.columns

Index(['marks', 'age'], dtype='object')

In [ ]:
df4.loc['raju']

marks    90
age      18
Name: raju, dtype: object

In [ ]:
df4.loc['raju','age']

'18'

In [ ]:
df4.iloc[0]

marks    90
age      18
Name: raju, dtype: object

In [ ]:
df4.reset_index(inplace=True)

In [ ]:
df4

name marks age
0    raju    90  18
1  aakash    65  21
2   raman    72  20
3  piyush    88  20

In [ ]:
df5=pd.read_csv('/content/titanic.csv')

In [ ]:
df5

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
886                              Montvila, Rev. Juozas    male  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch            Ticket     Fare Cabin Embarked  
0        0         A/5 21171   7.2500   NaN        S  
1        0          PC 17599  71.2833   C85        C  
2        0  STON/O2. 3101282   7.9250   NaN        S  
3        0            113803  53.1000  C123        S  
4        0            373450   8.0500   NaN        S  
..     ...               ...      ...   ...      ...  
886      0            211536  13.0000   NaN        S  
887      0            112053  30.0000   B42        S  
888      2        W./C. 6607  23.4500   NaN        S  
889      0            111369  30.0000  C148        C  
890      0            370376   7.7500   NaN        Q  

[891 rows x 12 columns]

In [ ]:
df5.set_index('PassengerId',inplace=True)

In [ ]:
df5.head()

Survived  Pclass  \
PassengerId                     
1                   0       3   
2                   1       1   
3                   1       3   
4                   1       1   
5                   0       3   

                                                          Name     Sex   Age  \
PassengerId                                                                    
1                                      Braund, Mr. Owen Harris    male  22.0   
2            Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0   
3                                       Heikkinen, Miss. Laina  female  26.0   
4                 Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0   
5                                     Allen, Mr. William Henry    male  35.0   

             SibSp  Parch            Ticket     Fare Cabin Embarked  
PassengerId                                                          
1                1      0         A/5 21171   7.2500   NaN        S  
2                1      0          PC 17599  71.2833   C85        C  
3                0      0  STON/O2. 3101282   7.9250   NaN        S  
4                1      0            113803  53.1000  C123        S  
5                0      0            373450   8.0500   NaN        S

In [ ]:
df5.columns

Index(['Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp', 'Parch', 'Ticket',
       'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [ ]:
df5.loc[3]

Survived                         1
Pclass                           3
Name        Heikkinen, Miss. Laina
Sex                         female
Age                           26.0
SibSp                            0
Parch                            0
Ticket            STON/O2. 3101282
Fare                         7.925
Cabin                          NaN
Embarked                         S
Name: 3, dtype: object

In [ ]:
df5.sort_index(ascending=False)            #sorting the index in descending order

Survived  Pclass  \
PassengerId                     
891                 0       3   
890                 1       1   
889                 0       3   
888                 1       1   
887                 0       2   
...               ...     ...   
5                   0       3   
4                   1       1   
3                   1       3   
2                   1       1   
1                   0       3   

                                                          Name     Sex   Age  \
PassengerId                                                                    
891                                        Dooley, Mr. Patrick    male  32.0   
890                                      Behr, Mr. Karl Howell    male  26.0   
889                   Johnston, Miss. Catherine Helen "Carrie"  female   NaN   
888                               Graham, Miss. Margaret Edith  female  19.0   
887                                      Montvila, Rev. Juozas    male  27.0   
...                                                        ...     ...   ...   
5                                     Allen, Mr. William Henry    male  35.0   
4                 Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0   
3                                       Heikkinen, Miss. Laina  female  26.0   
2            Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0   
1                                      Braund, Mr. Owen Harris    male  22.0   

             SibSp  Parch            Ticket     Fare Cabin Embarked  
PassengerId                                                          
891              0      0            370376   7.7500   NaN        Q  
890              0      0            111369  30.0000  C148        C  
889              1      2        W./C. 6607  23.4500   NaN        S  
888              0      0            112053  30.0000   B42        S  
887              0      0            211536  13.0000   NaN        S  
...            ...    ...               ...      ...   ...      ...  
5                0      0            373450   8.0500   NaN        S  
4                1      0            113803  53.1000  C123        S  
3                0      0  STON/O2. 3101282   7.9250   NaN        S  
2                1      0          PC 17599  71.2833   C85        C  
1                1      0         A/5 21171   7.2500   NaN        S  

[891 rows x 11 columns]

In [ ]:
df4

name marks age
0    raju    90  18
1  aakash    65  21
2   raman    72  20
3  piyush    88  20

In [ ]:
df5.head()

name marks age
0    raju    90  18
1  aakash    65  21
2   raman    72  20
3  piyush    88  20

In [ ]:
tf=df4['name']=='raju'

In [ ]:
df4[tf]       #conditional statement

name marks age
0  raju    90  18

In [ ]:
df4.loc[tf,'name']

0    raju
Name: name, dtype: object

In [ ]:
tf=(df4['name']=='raju') & (df4['age']=='18')      #using conditional as well as and operator

In [ ]:
df4[tf]

name marks age
0  raju    90  18

In [ ]:
df4[~tf]                #using not operator

name marks age
1  aakash    65  21
2   raman    72  20
3  piyush    88  20

In [ ]:
df5.head()

name marks age
0    raju    90  18
1  aakash    65  21
2   raman    72  20
3  piyush    88  20

In [ ]:
#old_age=(df5['Age']>60)

In [ ]:
old_age

PassengerId
1      False
2      False
3      False
4      False
5      False
       ...  
887    False
888    False
889    False
890    False
891    False
Name: Age, Length: 891, dtype: bool

In [ ]:
df4


name marks age
0    raju    90  18
1  aakash    65  21
2   raman    72  20
3  piyush    88  20

In [ ]:
df5.loc[old_age,['Name','Sex','Age']]

In [ ]:
df4

In [ ]:
df4.columns=['first','Marks','Age']

In [ ]:
df4

In [ ]:
df4.columns= [x.upper() for x in df4.columns]        #converting all the columns name into uppercase

In [ ]:
df4

In [ ]:
df4['FIRST']=[x.upper() for x in df4['FIRST']]       #converting all the columns into uppercase

In [ ]:
df4

In [ ]:
df4.columns=df4.columns.str.replace('R','_')         #replacing R char from all columns names

In [ ]:
df4

In [ ]:
df4.columns.str.replace('F','_')

In [ ]:
df4

In [ ]:
df4.loc[3]

In [ ]:
df4.loc[3]=['pintu','99','23']

In [ ]:
df4

In [ ]:
df4.loc[2,['FI_ST','AGE']]=['RAhul','24']

In [ ]:
df4

In [ ]:
df4.rename(columns={'FI_ST':'first','MA_KS':'marks'})

In [ ]:
df4

In [ ]:
df.drop('name', axis=1, inplace=True)


In [ ]:
df4

In [ ]:
df4.rename(columns={'FI_ST':'first','MA_KS':'marks'},inplace=True)   #renaming the column name

In [ ]:
df4

In [ ]:
df4.loc[3]

In [ ]:
df4.loc[3]=['chintu','80','20']

In [ ]:
df4

In [ ]:
df4.loc[4]=['intu','70','24']

In [ ]:
df4

In [ ]:
df4.loc[4,['first','AGE']]=['ramesh','23']

In [ ]:
df4

In [ ]:
df4.at[2,'AGE']='25'

In [ ]:
df4

In [ ]:
tf1=(df4['AGE']=='21')

In [ ]:
df4[tf1]['first']

In [ ]:
df4[~tf1]['first']

In [ ]:
df4[tf1]['AGE']='28'

In [ ]:
df4


In [ ]:
df4['first'].str.lower()

In [ ]:
df4

In [ ]:
df4=df4['first'].str.lower()

In [ ]:
df4

In [ ]:
#using apply functions


In [ ]:
df4=

In [ ]:
df4[first].apply(len)